<!-- <script src='http://requirejs.org/docs/release/2.1.1/comments/require.js'></script> -->
<script src='<?php echo $this->baseUrl ?>/public/scripts/lib/requirejs/2.1.1/require.js'></script>
<script>
	
	requirejs.config({
		// hack for IE
		enforceDefine: true,
		
		baseUrl: '<?php echo $this->baseUrl ?>/public/scripts',
			
		paths: {
			'jquery': [
				'http://code.jquery.com/jquery-1.9.1.min',
				// local load fallback
				'lib/jquery/1.9.1/jquery.min'
			],
			
			 // see https://github.com/jrburke/jqueryui-amd/tree/latest
			 // requires node.js to be installed to produce the amd version
			'jqueryui': 'lib/jqueryui/1.9.1-amd',

			'underscore': 'lib/underscore/1.4.4-amd/underscore',

			'backbone': 'lib/backbone/1.0.0-amd/backbone',
				 
			// jquery alert
			'utils': 'lib/utils',

			'mod': 'mod/backbone'
		}
//		locale: 'de-de'
	});
	
	require(
		['domReady!', 'jquery', '<?php echo isset($this->jsMain)?$this->jsMain:'main'?>'],
		function(doc, $, app) {
			$(doc).data('baseUrl', '<?php echo $this->baseUrl ?>');
			$(doc).data('APPLICATION_ENV', '<?php echo APPLICATION_ENV ?>');
			
			app.run();
		}
	);
	
</script>

