<?php $path = $this->baseUrl().(APPLICATION_ENV=='development'?'/development':'') ?>
<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en'>
<head>
	<meta http-equiv='content-type' content='text/html; charset=ISO-8859-1' />
	<title>Playground</title>
	<link rel='stylesheet' href='<?php echo $path ?>/styles/tree.app.css' />
<?php
//	<script src='http://requirejs.org/docs/release/0.15.0/minified/requireplugins-jquery-1.4.4.js'></script>

	// local copy
?>
	<script src='<?php echo $path ?>/scripts/http/requirejs.org/docs/release/0.15.0/minified/requireplugins-jquery-1.4.4.min.js'></script>
	<script>
	</script>
</head>
<body>
	<div id='library' class='container_16 ui-widget'>
		<div class='ui-widget-content grid_16'>
		
			<div class='grid_2'>&nbsp;
			</div>
			
			<div id='main' class='grid_12 alpha omega'><!-- need grid_12 here to give scrollable a width -->
<table width="100%" border="1">
  <colgroup span="2" align="left"></colgroup>
  <colgroup align="right" style="color:#0000FF;"></colgroup>
  <tr>
    <th>ISBN</th>
    <th>Title</th>
    <th>Price</th>
  </tr>
  <tr>
    <td>3476896</td>
    <td>My first HTML</td>
    <td>$53</td>
  </tr>
</table>
			</div>
			
			<div class='grid_2'>&nbsp;
			</div>
		</div>
		<div class='ui-helper-clearfix'></div>
	</div>
</body>
</html>
