<script src='http://requirejs.org/docs/release/2.1.1/comments/require.js'></script>
<script>
	
	requirejs.config({
	    // hack for IE
	    enforceDefine: true,
	    
		baseUrl: '<?php echo $this->baseUrl ?>/public/scripts',
			
		    paths: {
		        'jquery': [
		            'http://code.jquery.com/jquery-1.8.2.min',
		            // local load fallback
		            'lib/jquery/1.8.2/jquery.min.js'
		        ],
		        
			     // see https://github.com/jrburke/jqueryui-amd/tree/latest
			     // requires node.js to be installed to produce the amd version
		        'jqueryui': 'lib/jqueryui/1.9.1-amd',
		        
		        // jquery alert
		        'utils': 'lib/utils'     
		    },
//			locale: 'de-de'
		});
		
		require(
			['domReady!', 'jquery', '<?php echo isset($this->jsMain)?$this->jsMain:'main'?>'],
			
			function(doc, $) {
				$(doc).data('baseUrl', '<?php echo $this->baseUrl ?>');
				$(doc).data('APPLICATION_ENV', '<?php echo APPLICATION_ENV ?>');
			}
		);
	
</script>

