<div node_id='<?php echo $this->node_id ?>' name='<?php echo $this->name ?>'>
	<?php if (count($this->nodes)):?>
		<ul class='child_node_ref_list'>
			<?php foreach ($this->nodes as $node_id => $name):?>
				<li node_id='<?php echo $node_id ?>'><a href='#'><?php echo $name ?></a></li>
			<?php endforeach;?>
		</ul>
	<?php endif;?>
	<?php if (count($this->leafs)):?>	
		<ul class='leaf_ref_list'>
			<?php foreach ($this->leafs as $node_id => $name):?>
				<li node_id='<?php echo $node_id ?>'><a href='#'><?php echo $name ?></a></li>
			<?php endforeach;?>
		</ul>
	<?php endif;?>
</div>