<!DOCTYPE html>
<html>
<head>
	<meta http-equiv='content-type' content='text/html; charset=UTF-8' />
	<title>Playground</title>
	<link rel='stylesheet' href='<?php echo $this->baseUrl ?>/public/styles/tree.app.css' />
	<?php 
		$this->jsMain = 'tree.spine';
//		$this->jsMain = 'tree.prototype';
		echo $this->render('requirejs.phtml');
	?>
</head>
<body>
	<div id='library' class='container_16 ui-widget'>
		<div class='ui-widget-header grid_16'>
			<div class='grid_2 alpha'>
				<div id='pf'>Playground</div>
			</div>
			<div id='path_wrapper' class='grid_12'>
			</div>
			<div class='grid_2 omega'>
				<div id='safa-ri'>&#0931;&#0940;&#0966;&#0945;-&#0929;&#0942;<br />&copy;2013</div>
			</div>
		</div>
		<div class='ui-helper-clearfix'></div>
	</div>
	<?php 
		$this->initialPhtml = 'initialAjax.phtml';
		echo $this->render('system.phtml');
	?>
</body>
</html>
