<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Strict//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en'>
<head>
	<meta http-equiv='content-type' content='text/html; charset=UTF-8' />
	<title>Playground</title>
	<link rel='stylesheet' href='<?php echo $this->baseUrl ?>/public/styles/tree.app.css' />
	<?php 
		$this->jsMain = 'tree.menu';
		echo $this->render('requirejs.phtml');
	?>
</head>
<body>
	<button id="clickme" class="menu">click me</button>
	<ul id="menu">
		<li><a href="#">Aberdeen</a></li>
		<li><a href="#">Ada</a></li>
		<li><a href="#">Adamsville</a></li>
		<li><a href="#">Addyston</a></li>
		<li><a href="#">Adelphi</a></li>
	</ul>
</body>
</html>
